// examples/react-vite/src/App.tsx
import { Buffer } from 'buffer';
import { useState } from 'react';

import {
  BrokerClientId,
  BrokerRoutingType,
  RsocketBrokerClient,
  Tags,
} from 'rsocket-broker-client-js';
import type {
  ConnectionProperties,
  RequestProperties,
} from 'rsocket-broker-client-js';

const clientId = new BrokerClientId('11223344-5566-7788-99aa-bbccddeeff00');
const connectionTags = new Tags();
connectionTags.set(1, 'frontend=react');

const addressTags = new Tags();
addressTags.set(2, 'service=orders');

const client = new RsocketBrokerClient({
  webSocketFactory: (url) => new WebSocket(url),
});

const connectionProperties: ConnectionProperties = {
  token: 'replace-with-a-jwt',
  brokerUrl: 'ws://localhost:7171',
  brokerClientId: clientId,
  brokerClientName: 'react-example',
  connectionTags,
};

const requestProperties: RequestProperties = {
  token: 'replace-with-a-jwt',
  payload: Buffer.from(JSON.stringify({ orderId: 'demo-123' })),
  brokerClientId: clientId,
  route: 'orders.findById',
  brokerTargetName: 'orders-service',
  addressTags,
  addressMetadataTags: new Tags(),
  flags: BrokerRoutingType.UNICAST,
};

const metadata = client.addMetadata(
  requestProperties.token,
  requestProperties.brokerClientId,
  requestProperties.route,
  requestProperties.addressMetadataTags,
  requestProperties.addressTags,
  requestProperties.flags
);

const interactionExamples = [
  'await client.fireAndForget(rsocket, requestProperties.payload.toString(), metadata);',
  '',
  'const response = client.requestResponse(',
  '  rsocket,',
  '  requestProperties.payload.toString(),',
  '  metadata',
  ');',
  '',
  'const stream = client.requestStream(',
  '  rsocket,',
  '  requestProperties.payload.toString(),',
  '  metadata',
  ');',
  '',
  'const channel = client.requestChannel(',
  '  rsocket,',
  '  of(requestProperties.payload.toString()),',
  '  metadata',
  ');',
].join('\n');

export default function App() {
  const [connectionStatus, setConnectionStatus] =
    useState('Not connected yet.');
  const [connectionError, setConnectionError] = useState<string | null>(null);

  async function connectToBroker(): Promise<void> {
    setConnectionStatus('Connecting...');
    setConnectionError(null);

    try {
      const rsocket = await client.connect(connectionProperties);

      setConnectionStatus(
        `Connected. RSocket close method available: ${String(
          typeof rsocket.close === 'function'
        )}`
      );
    } catch (error) {
      const message =
        error instanceof Error ? error.message : 'Unknown connection error';

      setConnectionStatus('Connection failed.');
      setConnectionError(message);
    }
  }

  return (
    <main className="page">
      <section className="card">
        <p className="eyebrow">React 19 + Vite 8</p>
        <h1>RSocket Broker Client</h1>
        <p className="lede">
          This example verifies that the package can be imported, configured,
          and used to create a live broker connection from a current React app.
        </p>

        <dl className="grid">
          <div>
            <dt>Client name</dt>
            <dd>{connectionProperties.brokerClientName}</dd>
          </div>
          <div>
            <dt>Broker URL</dt>
            <dd>{connectionProperties.brokerUrl}</dd>
          </div>
          <div>
            <dt>Routing mode</dt>
            <dd>{requestProperties.flags}</dd>
          </div>
          <div>
            <dt>Metadata entries</dt>
            <dd>{metadata.size}</dd>
          </div>
        </dl>

        <div className="actions">
          <button className="button" type="button" onClick={connectToBroker}>
            Connect to broker
          </button>
          <p className="status">{connectionStatus}</p>
          {connectionError ? <p className="error">{connectionError}</p> : null}
        </div>

        <pre className="code">
          <code>
            {[
              'const rsocket = await client.connect(connectionProperties);',
              '',
              interactionExamples,
            ].join('\n')}
          </code>
        </pre>
      </section>
    </main>
  );
}

// examples/angular-standalone/src/app/app.ts
import { Buffer } from 'buffer';
import { Component } from '@angular/core';
import {
  BrokerClientId,
  BrokerRoutingType,
  RsocketBrokerClient,
  Tags,
} from 'rsocket-broker-client-js';
import type {
  ConnectionProperties,
  RequestProperties,
} from 'rsocket-broker-client-js';

@Component({
  selector: 'app-root',
  templateUrl: './app.html',
  styleUrl: './app.css',
})
export class App {
  protected connectionStatus = 'Not connected yet.';
  protected connectionError: string | null = null;

  protected readonly clientId = new BrokerClientId(
    '11223344-5566-7788-99aa-bbccddeeff00'
  );

  protected readonly connectionTags = (() => {
    const tags = new Tags();
    tags.set(1, 'frontend=angular');
    return tags;
  })();

  protected readonly addressTags = (() => {
    const tags = new Tags();
    tags.set(2, 'service=orders');
    return tags;
  })();

  protected readonly client = new RsocketBrokerClient({
    webSocketFactory: (url) => new WebSocket(url),
  });

  protected readonly connectionProperties: ConnectionProperties = {
    token: 'replace-with-a-jwt',
    brokerUrl: 'ws://localhost:7171',
    brokerClientId: this.clientId,
    brokerClientName: 'angular-example',
    connectionTags: this.connectionTags,
  };

  protected readonly requestProperties: RequestProperties = {
    token: 'replace-with-a-jwt',
    payload: Buffer.from(JSON.stringify({ orderId: 'demo-123' })),
    brokerClientId: this.clientId,
    route: 'orders.findById',
    brokerTargetName: 'orders-service',
    addressTags: this.addressTags,
    addressMetadataTags: new Tags(),
    flags: BrokerRoutingType.UNICAST,
  };

  protected readonly metadata = this.client.addMetadata(
    this.requestProperties.token,
    this.requestProperties.brokerClientId,
    this.requestProperties.route,
    this.requestProperties.addressMetadataTags,
    this.requestProperties.addressTags,
    this.requestProperties.flags
  );

  protected readonly interactionExamples = [
    'await client.fireAndForget(rsocket, requestProperties.payload.toString(), metadata);',
    '',
    'const response = client.requestResponse(',
    '  rsocket,',
    '  requestProperties.payload.toString(),',
    '  metadata',
    ');',
    '',
    'const stream = client.requestStream(',
    '  rsocket,',
    '  requestProperties.payload.toString(),',
    '  metadata',
    ');',
    '',
    'const channel = client.requestChannel(',
    '  rsocket,',
    '  of(requestProperties.payload.toString()),',
    '  metadata',
    ');',
  ].join('\n');

  protected async connectToBroker(): Promise<void> {
    this.connectionStatus = 'Connecting...';
    this.connectionError = null;

    try {
      const rsocket = await this.client.connect(this.connectionProperties);

      this.connectionStatus = `Connected. RSocket close method available: ${String(
        typeof rsocket.close === 'function'
      )}`;
    } catch (error) {
      const message =
        error instanceof Error ? error.message : 'Unknown connection error';

      this.connectionStatus = 'Connection failed.';
      this.connectionError = message;
    }
  }
}
